### ISSUE TITLE
Criação da Logo

### ISSUE THREAD

**Issue by RafaelMassoni** [hatflix/hatflix#5]
É preciso editar uma logo para o Hatflix e dar upload no GitHub nas imagens relacionadas ao projeto.

A Logo será uma combinação de duas logos famosas: a logo do [Netflix](https://t2.tudocdn.net/178296?w=660&h=660) e a logo do [Red Hat](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Red_Hat_logo.svg/220px-Red_Hat_logo.svg.png).

A ideia é que o chapéu do Red Hat "encaixe" acima do "H" do Hatflix.

[Chapéu alternativo do Red Hat](https://logodownload.org/wp-content/uploads/2017/10/red-hat-logo.png)

**Comment by RafaelMassoni** [comment]
Fiz a seguinte logo:

![hatflix](https://user-images.githubusercontent.com/73971077/162844426-690dfc1b-0bee-4d46-8eeb-c2af392fcd93.jpg)

O que acham? @tomtomesteves @marco-silveira @ZASUO01

**Comment by tomtomesteves** [comment]
Ficou top !

**Comment by ZASUO01** [comment]
Boa, o chapéu serviu!

**Comment by marco-silveira** [comment]
Ficou show!
